/**
 * ISO 3166 Alpha 2
 */
export const ISO_3166_Alpha_2 = [
    {v: 'AF', n: 'Afghanistan'},
    {v: 'AX', n: 'Åland Islands'},
    {v: 'AL', n: 'Albania'},
    {v: 'DZ', n: 'Algeria'},
    {v: 'AS', n: 'American Samoa'},
    {v: 'AD', n: 'Andorra'},
    {v: 'AO', n: 'Angola'},
    {v: 'AI', n: 'Anguilla'},
    {v: 'AQ', n: 'Antarctica'},
    {v: 'AG', n: 'Antigua and Barbuda'},
    {v: 'AR', n: 'Argentina'},
    {v: 'AM', n: 'Armenia'},
    {v: 'AW', n: 'Aruba'},
    {v: 'AU', n: 'Australia'},
    {v: 'AT', n: 'Austria'},
    {v: 'AZ', n: 'Azerbaijan'},
    {v: 'BS', n: 'Bahamas'},
    {v: 'BH', n: 'Bahrain'},
    {v: 'BD', n: 'Bangladesh'},
    {v: 'BB', n: 'Barbados'},
    {v: 'BY', n: 'Belarus'},
    {v: 'BE', n: 'Belgium'},
    {v: 'BZ', n: 'Belize'},
    {v: 'BJ', n: 'Benin'},
    {v: 'BM', n: 'Bermuda'},
    {v: 'BT', n: 'Bhutan'},
    {v: 'BO', n: 'Bolivia, Plurinational State of'},
    {v: 'BQ', n: 'Bonaire, Sint Eustatius and Saba'},
    {v: 'BA', n: 'Bosnia and Herzegovina'},
    {v: 'BW', n: 'Botswana'},
    {v: 'BV', n: 'Bouvet Island'},
    {v: 'BR', n: 'Brazil'},
    {v: 'IO', n: 'British Indian Ocean Territory'},
    {v: 'BN', n: 'Brunei Darussalam'},
    {v: 'BG', n: 'Bulgaria'},
    {v: 'BF', n: 'Burkina Faso'},
    {v: 'BI', n: 'Burundi'},
    {v: 'KH', n: 'Cambodia'},
    {v: 'CM', n: 'Cameroon'},
    {v: 'CA', n: 'Canada'},
    {v: 'CV', n: 'Cape Verde'},
    {v: 'KY', n: 'Cayman Islands'},
    {v: 'CF', n: 'Central African Republic'},
    {v: 'TD', n: 'Chad'},
    {v: 'CL', n: 'Chile'},
    {v: 'CN', n: 'China'},
    {v: 'CX', n: 'Christmas Island'},
    {v: 'CC', n: 'Cocos (Keeling) Islands'},
    {v: 'CO', n: 'Colombia'},
    {v: 'KM', n: 'Comoros'},
    {v: 'CG', n: 'Congo'},
    {v: 'CD', n: 'Congo, the Democratic Republic of the'},
    {v: 'CK', n: 'Cook Islands'},
    {v: 'CR', n: 'Costa Rica'},
    {v: 'CI', n: 'Côte d\'Ivoire'},
    {v: 'HR', n: 'Croatia'},
    {v: 'CU', n: 'Cuba'},
    {v: 'CW', n: 'Curaçao'},
    {v: 'CY', n: 'Cyprus'},
    {v: 'CZ', n: 'Czech Republic'},
    {v: 'DK', n: 'Denmark'},
    {v: 'DJ', n: 'Djibouti'},
    {v: 'DM', n: 'Dominica'},
    {v: 'DO', n: 'Dominican Republic'},
    {v: 'EC', n: 'Ecuador'},
    {v: 'EG', n: 'Egypt'},
    {v: 'SV', n: 'El Salvador'},
    {v: 'GQ', n: 'Equatorial Guinea'},
    {v: 'ER', n: 'Eritrea'},
    {v: 'EE', n: 'Estonia'},
    {v: 'ET', n: 'Ethiopia'},
    {v: 'FK', n: 'Falkland Islands (Malvinas)'},
    {v: 'FO', n: 'Faroe Islands'},
    {v: 'FJ', n: 'Fiji'},
    {v: 'FI', n: 'Finland'},
    {v: 'FR', n: 'France'},
    {v: 'GF', n: 'French Guiana'},
    {v: 'PF', n: 'French Polynesia'},
    {v: 'TF', n: 'French Southern Territories'},
    {v: 'GA', n: 'Gabon'},
    {v: 'GM', n: 'Gambia'},
    {v: 'GE', n: 'Georgia'},
    {v: 'DE', n: 'Germany'},
    {v: 'GH', n: 'Ghana'},
    {v: 'GI', n: 'Gibraltar'},
    {v: 'GR', n: 'Greece'},
    {v: 'GL', n: 'Greenland'},
    {v: 'GD', n: 'Grenada'},
    {v: 'GP', n: 'Guadeloupe'},
    {v: 'GU', n: 'Guam'},
    {v: 'GT', n: 'Guatemala'},
    {v: 'GG', n: 'Guernsey'},
    {v: 'GN', n: 'Guinea'},
    {v: 'GW', n: 'Guinea-Bissau'},
    {v: 'GY', n: 'Guyana'},
    {v: 'HT', n: 'Haiti'},
    {v: 'HM', n: 'Heard Island and McDonald Islands'},
    {v: 'VA', n: 'Holy See (Vatican City State)'},
    {v: 'HN', n: 'Honduras'},
    {v: 'HK', n: 'Hong Kong'},
    {v: 'HU', n: 'Hungary'},
    {v: 'IS', n: 'Iceland'},
    {v: 'IN', n: 'India'},
    {v: 'ID', n: 'Indonesia'},
    {v: 'IR', n: 'Iran, Islamic Republic of'},
    {v: 'IQ', n: 'Iraq'},
    {v: 'IE', n: 'Ireland'},
    {v: 'IM', n: 'Isle of Man'},
    {v: 'IL', n: 'Israel'},
    {v: 'IT', n: 'Italy'},
    {v: 'JM', n: 'Jamaica'},
    {v: 'JP', n: 'Japan'},
    {v: 'JE', n: 'Jersey'},
    {v: 'JO', n: 'Jordan'},
    {v: 'KZ', n: 'Kazakhstan'},
    {v: 'KE', n: 'Kenya'},
    {v: 'KI', n: 'Kiribati'},
    {v: 'KP', n: 'Korea, Democratic People\'s Republic of'},
    {v: 'KR', n: 'Korea, Republic of'},
    {v: 'KW', n: 'Kuwait'},
    {v: 'KG', n: 'Kyrgyzstan'},
    {v: 'LA', n: 'Lao People\'s Democratic Republic'},
    {v: 'LV', n: 'Latvia'},
    {v: 'LB', n: 'Lebanon'},
    {v: 'LS', n: 'Lesotho'},
    {v: 'LR', n: 'Liberia'},
    {v: 'LY', n: 'Libya'},
    {v: 'LI', n: 'Liechtenstein'},
    {v: 'LT', n: 'Lithuania'},
    {v: 'LU', n: 'Luxembourg'},
    {v: 'MO', n: 'Macao'},
    {v: 'MK', n: 'Macedonia, the former Yugoslav Republic of'},
    {v: 'MG', n: 'Madagascar'},
    {v: 'MW', n: 'Malawi'},
    {v: 'MY', n: 'Malaysia'},
    {v: 'MV', n: 'Maldives'},
    {v: 'ML', n: 'Mali'},
    {v: 'MT', n: 'Malta'},
    {v: 'MH', n: 'Marshall Islands'},
    {v: 'MQ', n: 'Martinique'},
    {v: 'MR', n: 'Mauritania'},
    {v: 'MU', n: 'Mauritius'},
    {v: 'YT', n: 'Mayotte'},
    {v: 'MX', n: 'Mexico'},
    {v: 'FM', n: 'Micronesia, Federated States of'},
    {v: 'MD', n: 'Moldova, Republic of'},
    {v: 'MC', n: 'Monaco'},
    {v: 'MN', n: 'Mongolia'},
    {v: 'ME', n: 'Montenegro'},
    {v: 'MS', n: 'Montserrat'},
    {v: 'MA', n: 'Morocco'},
    {v: 'MZ', n: 'Mozambique'},
    {v: 'MM', n: 'Myanmar'},
    {v: 'NA', n: 'Namibia'},
    {v: 'NR', n: 'Nauru'},
    {v: 'NP', n: 'Nepal'},
    {v: 'NL', n: 'Netherlands'},
    {v: 'NC', n: 'New Caledonia'},
    {v: 'NZ', n: 'New Zealand'},
    {v: 'NI', n: 'Nicaragua'},
    {v: 'NE', n: 'Niger'},
    {v: 'NG', n: 'Nigeria'},
    {v: 'NU', n: 'Niue'},
    {v: 'NF', n: 'Norfolk Island'},
    {v: 'MP', n: 'Northern Mariana Islands'},
    {v: 'NO', n: 'Norway'},
    {v: 'OM', n: 'Oman'},
    {v: 'PK', n: 'Pakistan'},
    {v: 'PW', n: 'Palau'},
    {v: 'PS', n: 'Palestinian Territory, Occupied'},
    {v: 'PA', n: 'Panama'},
    {v: 'PG', n: 'Papua New Guinea'},
    {v: 'PY', n: 'Paraguay'},
    {v: 'PE', n: 'Peru'},
    {v: 'PH', n: 'Philippines'},
    {v: 'PN', n: 'Pitcairn'},
    {v: 'PL', n: 'Polska'},
    {v: 'PT', n: 'Portugal'},
    {v: 'PR', n: 'Puerto Rico'},
    {v: 'QA', n: 'Qatar'},
    {v: 'RE', n: 'Réunion'},
    {v: 'RO', n: 'Romania'},
    {v: 'RU', n: 'Russian Federation'},
    {v: 'RW', n: 'Rwanda'},
    {v: 'BL', n: 'Saint Barthélemy'},
    {v: 'SH', n: 'Saint Helena, Ascension and Tristan da Cunha'},
    {v: 'KN', n: 'Saint Kitts and Nevis'},
    {v: 'LC', n: 'Saint Lucia'},
    {v: 'MF', n: 'Saint Martin (French part)'},
    {v: 'PM', n: 'Saint Pierre and Miquelon'},
    {v: 'VC', n: 'Saint Vincent and the Grenadines'},
    {v: 'WS', n: 'Samoa'},
    {v: 'SM', n: 'San Marino'},
    {v: 'ST', n: 'Sao Tome and Principe'},
    {v: 'SA', n: 'Saudi Arabia'},
    {v: 'SN', n: 'Senegal'},
    {v: 'RS', n: 'Serbia'},
    {v: 'SC', n: 'Seychelles'},
    {v: 'SL', n: 'Sierra Leone'},
    {v: 'SG', n: 'Singapore'},
    {v: 'SX', n: 'Sint Maarten (Dutch part)'},
    {v: 'SK', n: 'Slovakia'},
    {v: 'SI', n: 'Slovenia'},
    {v: 'SB', n: 'Solomon Islands'},
    {v: 'SO', n: 'Somalia'},
    {v: 'ZA', n: 'South Africa'},
    {v: 'GS', n: 'South Georgia and the South Sandwich Islands'},
    {v: 'SS', n: 'South Sudan'},
    {v: 'ES', n: 'Spain'},
    {v: 'LK', n: 'Sri Lanka'},
    {v: 'SD', n: 'Sudan'},
    {v: 'SR', n: 'Suriname'},
    {v: 'SJ', n: 'Svalbard and Jan Mayen'},
    {v: 'SZ', n: 'Swaziland'},
    {v: 'SE', n: 'Sweden'},
    {v: 'CH', n: 'Switzerland'},
    {v: 'SY', n: 'Syrian Arab Republic'},
    {v: 'TW', n: 'Taiwan, Province of China'},
    {v: 'TJ', n: 'Tajikistan'},
    {v: 'TZ', n: 'Tanzania, United Republic of'},
    {v: 'TH', n: 'Thailand'},
    {v: 'TL', n: 'Timor-Leste'},
    {v: 'TG', n: 'Togo'},
    {v: 'TK', n: 'Tokelau'},
    {v: 'TO', n: 'Tonga'},
    {v: 'TT', n: 'Trinidad and Tobago'},
    {v: 'TN', n: 'Tunisia'},
    {v: 'TR', n: 'Turkey'},
    {v: 'TM', n: 'Turkmenistan'},
    {v: 'TC', n: 'Turks and Caicos Islands'},
    {v: 'TV', n: 'Tuvalu'},
    {v: 'UG', n: 'Uganda'},
    {v: 'UA', n: 'Ukraine'},
    {v: 'AE', n: 'United Arab Emirates'},
    {v: 'GB', n: 'United Kingdom'},
    {v: 'US', n: 'United States'},
    {v: 'UM', n: 'United States Minor Outlying Islands'},
    {v: 'UY', n: 'Uruguay'},
    {v: 'UZ', n: 'Uzbekistan'},
    {v: 'VU', n: 'Vanuatu'},
    {v: 'VE', n: 'Venezuela, Bolivarian Republic of'},
    {v: 'VN', n: 'Viet Nam'},
    {v: 'VG', n: 'Virgin Islands, British'},
    {v: 'VI', n: 'Virgin Islands, U.S.'},
    {v: 'WF', n: 'Wallis and Futuna'},
    {v: 'EH', n: 'Western Sahara'},
    {v: 'YE', n: 'Yemen'},
    {v: 'ZM', n: 'Zambia'},
    {v: 'ZW', n: 'Zimbabwe'}
];
